name: Deploy Ellen Joe Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Pull code from GitHub to EC2
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Copy file from GitHub to EC2 (using SCP)
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          exclude: ".git,.github,.env,venv"
          target: ${{ secrets.PROJECT_PATH }}
          rm: false

      # Step 3: SSH connection to EC2 to install pip packages and restart the bot
      - name: Install Dependencies & Restart Bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            source venv/bin/activate
            pip install -r requirements.txt
            pgrep -f "src.bot" | grep -v $$ | xargs -r kill -9 || true
            sleep 2
            nohup python -u -m src.bot > bot_output.log 2>&1 &
            echo "✅ Deployment Completed: Bot has been restarted."